export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const ADD_USER = 'ADD_USER'

export const SET_ACTIVE_WINDOW = 'SET_ACTIVE_WINDOW'

export const SET_UPDATE_POPUP = 'SET_UPDATE_POPUP'

export const SET_ADD_POPUP = 'SET_ADD_POPUP'

export const PASS_ID = 'PASS_ID' 